USE [master]
GO

/****** Object:  Database [Poslasticarnica]    Script Date: 5/30/2020 7:18:20 PM ******/
CREATE DATABASE [Poslasticarnica]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Poslasticarnica', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Poslasticarnica.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Poslasticarnica_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Poslasticarnica_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Poslasticarnica].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Poslasticarnica] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Poslasticarnica] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Poslasticarnica] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Poslasticarnica] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Poslasticarnica] SET ARITHABORT OFF 
GO

ALTER DATABASE [Poslasticarnica] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Poslasticarnica] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Poslasticarnica] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Poslasticarnica] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Poslasticarnica] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Poslasticarnica] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Poslasticarnica] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Poslasticarnica] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Poslasticarnica] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Poslasticarnica] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Poslasticarnica] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Poslasticarnica] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Poslasticarnica] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Poslasticarnica] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Poslasticarnica] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Poslasticarnica] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Poslasticarnica] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Poslasticarnica] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Poslasticarnica] SET  MULTI_USER 
GO

ALTER DATABASE [Poslasticarnica] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Poslasticarnica] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Poslasticarnica] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Poslasticarnica] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Poslasticarnica] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Poslasticarnica] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Poslasticarnica] SET  READ_WRITE 
GO

